concealer_type: list_reverse
concealer_vad_config: webrtc_concealer_20260218.yaml
shortlist_maxlen: 100
max_countdown_reuse: 10  # in number of uses
max_concealer_distance_to_buffer: 0  # in number of concealers
concealer_duration: 0.150
concealing_min_timeout_duration: 0.050
concealing_max_timeout_duration: 0.150
fade_duration: 0.030